
//generated by meteor

import { FlowRouter } from 'meteor/kadira:flow-router';
import { BlazeLayout } from 'meteor/kadira:blaze-layout';

// Import needed templates
import '../../ui/layouts/body/body.js';
import '../../ui/pages/home/home.js';
import '../../ui/pages/not-found/not-found.js';

// Set up all routes in the app
FlowRouter.route('/', {
  name: 'App.home',
  action() {
    BlazeLayout.render('App_body', { main: 'App_home' });
  },
});

FlowRouter.notFound = {
  action() {
    BlazeLayout.render('App_body', { main: 'App_notFound' });
  },
};

FlowRouter.route('/categories', {
    name: 'Stream',
    action() {
        BlazeLayout.render("App_body", {main: "showCategories"});
    }
});

FlowRouter.route('/category/:_id', {
    name: 'Stream',
    action() {
        BlazeLayout.render("App_body", {main: "singleCategory"});
    }
});

// Route for

// FlowRouter.route('/createPosts', {
//     name: 'Stream',
//     action() {
//         BlazeLayout.render("App_body", {main: "postCreate"});
//     }
// });

// FlowRouter.route('/posted', {
//     name: 'Stream',
//     action() {
//         BlazeLayout.render("App_body", {main: "shownPosts"});
//     }
// });

// FlowRouter.route('/post/:_id', {
//     name: 'Posts',
//     action() {
//         BlazeLayout.render("App_body", {main: "singlePost"});
//     }
// });

// FlowRouter.route('/insert', {
//     name: 'Posts',
//     action() {
//         BlazeLayout.render("App_body", {main: "insertCategory"});
//     }
// });

// FlowRouter.route('/single', {
//     name: 'Stream',
//     action() {
//         BlazeLayout.render("App_body", {main: "single"});
//     }
// });

// FlowRouter.route('/allCategories', {
//     name: 'Stream',
//     action() {
//         BlazeLayout.render("App_body", {main: "categoryCreate"});
//     }
// });

// FlowRouter.route('/posti', {
//     name: 'Stream',
//     action() {
//         BlazeLayout.render("App_body", {main: "posting"});
//     }
// });
